import { describe, it, expect } from "vitest";

import { buildTicketText } from "./ticketBuilder";

// Golden tests: congelan la salida byte-a-byte de buildTicketText.
// Las fechas se fijan siempre en ISO para mantener determinismo; el TZ
// America/Cancun es intencional y parte de la salida congela su formato.

const BASE_BRANCH = {
  name: "Sucursal Centro",
  phone: "998 111 2233",
  address: "Av. Xuchil 5, SM 34",
  city: "Cancún",
  state: "QUINTANA ROO",
  postal_code: "77500",
};

const BASE_FOOTER = {
  line1: "Gracias por su compra",
  line2: "Agenda tu cita de baño",
  phone: "998 117 5387",
  returnPolicy: "Para cambios o devoluciones presentar ticket de compra",
};

describe("buildTicketText (golden)", () => {
  it("1. venta simple en efectivo", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA001",
        created_at: "2026-09-15T18:30:00.000Z",
        subtotal: 200,
        tax: 32,
        total: 232,
        amount_received: 250,
        change_amount: 18,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 250, currency: "MXN" }],
        status: "completed",
      },
      items: [
        { quantity: 2, description: "Croquetas Premium", unit_price: 80, original_unit_price: 80, final_unit_price: 80, line_total: 160 },
        { quantity: 1, description: "Snack", unit_price: 40, original_unit_price: 40, final_unit_price: 40, line_total: 40 },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 15/9/2026",
      "Hora : 01:30 p.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA001",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "2    CROQUETAS PREMIUM    160.00",
      "     P.U. $80.00",
      "",
      "1    SNACK                 40.00",
      "     P.U. $40.00",
      "",
      "--------------------------------",
      "Artículos: 3",
      "Subtotal:                $200.00",
      "IVA 16%:                  $32.00",
      "TOTAL:                   $232.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $250.00",
      "Pago con:                $250.00",
      "Cambio:                   $18.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("2. pago mixto (MIXTO)", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA002",
        created_at: "2026-09-15T19:00:00.000Z",
        subtotal: 150,
        tax: 24,
        total: 174,
        amount_received: 174,
        change_amount: 0,
        payment_method: "MIXTO",
        payments: [
          { payment_method_name: "Efectivo", amount: 100 },
          { payment_method_name: "Tarjeta", amount: 74 },
        ],
        status: "completed",
      },
      items: [{ quantity: 1, description: "Juguete", unit_price: 174, line_total: 174 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 15/9/2026",
      "Hora : 02:00 p.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA002",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    JUGUETE              174.00",
      "     P.U. $174.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $150.00",
      "IVA 16%:                  $24.00",
      "TOTAL:                   $174.00",
      "--------------------------------",
      "Método de pago: MIXTO",
      "EFECTIVO:                $100.00",
      "TARJETA:                  $74.00",
      "Pago con:                $174.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("3. pago USD con exchange_rate", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA003",
        created_at: "2026-09-15T20:00:00.000Z",
        subtotal: 340,
        tax: 54.4,
        total: 394.4,
        amount_received: 394.4,
        change_amount: 0,
        payment_method: "USD",
        payments: [{ payment_method_name: "Dólares", amount: 20, currency: "USD", exchange_rate: 19.72 }],
        status: "completed",
      },
      items: [{ quantity: 1, description: "Correa", unit_price: 394.4, line_total: 394.4 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 15/9/2026",
      "Hora : 03:00 p.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA003",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    CORREA               394.40",
      "     P.U. $394.40",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $340.00",
      "IVA 16%:                  $54.40",
      "TOTAL:                   $394.40",
      "--------------------------------",
      "Método de pago: DÓLARES",
      "DÓLARES USD:              $20.00",
      "T.C. USD:                 $19.72",
      "EQ. MXN USD:             $394.40",
      "Pago con:                $394.40",
      "Cambio:                    $0.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("4. recompensa product_discount", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA004",
        created_at: "2026-09-16T15:00:00.000Z",
        subtotal: 200,
        tax: 0,
        total: 160,
        discount_total: 40,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 160 }],
        status: "completed",
        reward_points_used: 40,
        rewards_count: 1,
        has_reward_redemptions: true,
        reward_redemptions: [
          { reward_name: "Descuento 20%", product_name: "Croquetas", quantity: 1, total_points: 40, unit_price: 200, discount_amount: 40, reward_type: "product_discount", points_per_unit: 40 },
        ],
      },
      items: [
        { quantity: 1, description: "Croquetas", unit_price: 200, original_unit_price: 200, final_unit_price: 160, line_total: 160, reward_id: "R001", reward_discount_amount: 40, reward_name: "Descuento 20%" },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 10:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA004",
      "Cliente: PÚBLICO EN GENERAL",
      "Incluye recompensa aplicada",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    CROQUETAS (DESC.     160.00",
      "     RECOMP.)                   ",
      "     Descuento recompensa",
      "     Precio orig. $200.00",
      "     Desc. $40.00 c/u",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $200.00",
      "Descuento:               -$40.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $160.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $160.00",
      "Pago con:                $160.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "     RECOMPENSAS CANJEADAS      ",
      "Canjes aplicados:              1",
      "Puntos usados:               -40",
      "--------------------------------",
      "Canje #1",
      "DESCUENTO 20%",
      "Tipo: DESCUENTO EN PRODUCTO",
      "Descuento:               -$40.00",
      "Producto: CROQUETAS",
      "Cantidad:                     x1",
      "Puntos:                      -40",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("5. recompensa free_product", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA005",
        created_at: "2026-09-16T16:00:00.000Z",
        subtotal: 150,
        tax: 0,
        total: 150,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 150 }],
        status: "completed",
        reward_points_used: 0,
        rewards_count: 1,
        has_reward_redemptions: true,
        reward_redemptions: [
          { reward_name: "Producto gratis", product_name: "Collarin", quantity: 1, total_points: 0, unit_price: 0, discount_amount: 0, reward_type: "free_product", points_per_unit: 0 },
        ],
      },
      items: [
        { quantity: 1, description: "Collar", unit_price: 150, original_unit_price: 150, final_unit_price: 150, line_total: 150 },
        { quantity: 1, description: "Collarin", unit_price: 0, original_unit_price: 80, final_unit_price: 0, line_total: 0, is_reward_item: true, reward_id: "R002", reward_name: "Producto gratis" },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 11:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA005",
      "Cliente: PÚBLICO EN GENERAL",
      "Incluye recompensa aplicada",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    COLLAR               150.00",
      "     P.U. $150.00",
      "",
      "1    COLLARIN               0.00",
      "     (RECOMPENSA)               ",
      "     Valor $80.00",
      "     Canje por puntos",
      "",
      "--------------------------------",
      "Artículos: 2",
      "Subtotal:                $150.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $150.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $150.00",
      "Pago con:                $150.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "     RECOMPENSAS CANJEADAS      ",
      "Canjes aplicados:              1",
      "--------------------------------",
      "Canje #1",
      "PRODUCTO GRATIS",
      "Tipo: PRODUCTO GRATIS",
      "Producto: COLLARIN",
      "Cantidad:                     x1",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("6. venta solo-recompensa (SIN PAGO)", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA006",
        created_at: "2026-09-16T17:00:00.000Z",
        subtotal: 0,
        tax: 0,
        total: 0,
        amount_received: 0,
        change_amount: 0,
        payment_method: "SIN PAGO",
        payments: [],
        status: "completed",
        is_reward_redemption_only: true,
        reward_points_used: 60,
        rewards_count: 1,
        has_reward_redemptions: true,
        reward_redemptions: [
          { reward_name: "Croquetas gratis", product_name: "Croquetas", quantity: 1, total_points: 60, unit_price: 120, discount_amount: 120, reward_type: "free_product", points_per_unit: 60 },
        ],
      },
      items: [
        { quantity: 1, description: "Croquetas", unit_price: 0, original_unit_price: 120, final_unit_price: 0, line_total: 0, is_reward_item: true, reward_id: "R003", reward_name: "Croquetas gratis" },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 12:00 p.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA006",
      "Cliente: PÚBLICO EN GENERAL",
      "Operación: CANJE DE RECOMPENSA",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    CROQUETAS (DESC.       0.00",
      "     RECOMP.)                   ",
      "     Descuento recompensa",
      "     Precio orig. $120.00",
      "     Desc. $120.00 c/u",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                  $0.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                     $0.00",
      "--------------------------------",
      "Método de pago: SIN PAGO",
      "--------------------------------",
      "     RECOMPENSAS CANJEADAS      ",
      "Canjes aplicados:              1",
      "Puntos usados:               -60",
      "--------------------------------",
      "Canje #1",
      "CROQUETAS GRATIS",
      "Tipo: DESCUENTO EN PRODUCTO",
      "Producto: CROQUETAS",
      "Cantidad:                     x1",
      "Puntos:                      -60",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("7. venta cancelada (motivo + método reembolso)", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA007",
        created_at: "2026-09-16T10:00:00.000Z",
        cancelled_at: "2026-09-16T11:30:00.000Z",
        subtotal: 200,
        tax: 32,
        total: 232,
        status: "cancelled",
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 232 }],
        cancellation_reason: "Error en la orden",
        refund_method: "Efectivo",
      },
      items: [{ quantity: 1, description: "Arena", unit_price: 232, original_unit_price: 232, final_unit_price: 232, line_total: 232 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 05:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA007",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    ARENA                232.00",
      "     P.U. $232.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $200.00",
      "IVA 16%:                  $32.00",
      "TOTAL:                   $232.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $232.00",
      "Pago con:                $232.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "    *** VENTA CANCELADA ***     ",
      "Fecha cancelación: 16/9/2026",
      "Hora cancelación : 06:30 a.m.",
      "Motivo:",
      "Error en la orden",
      "Método reembolso: EFECTIVO",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("8. venta cancelada con recompensa revertida", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA008",
        created_at: "2026-09-16T12:00:00.000Z",
        cancelled_at: "2026-09-16T12:45:00.000Z",
        subtotal: 200,
        tax: 0,
        total: 160,
        discount_total: 40,
        status: "cancelled",
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 160 }],
        cancellation_reason: "Cliente canceló",
        refund_method: "Transferencia",
        reward_points_used: 40,
        rewards_count: 1,
        has_reward_redemptions: true,
        reward_redemptions: [
          { reward_name: "Descuento 20%", product_name: "Croquetas", quantity: 1, total_points: 40, unit_price: 200, discount_amount: 40, reward_type: "product_discount", points_per_unit: 40, reversed_at: "2026-09-16T13:00:00.000Z", reversal_reason: "Reverso por cancelación" },
        ],
      },
      items: [
        { quantity: 1, description: "Croquetas", unit_price: 200, original_unit_price: 200, final_unit_price: 160, line_total: 160, reward_id: "R001", reward_discount_amount: 40, reward_name: "Descuento 20%" },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 07:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA008",
      "Cliente: PÚBLICO EN GENERAL",
      "Incluye recompensa revertida",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    CROQUETAS (DESC.     160.00",
      "     RECOMP.)                   ",
      "     Descuento recompensa",
      "     Precio orig. $200.00",
      "     Desc. $40.00 c/u",
      "     Recompensa revertida",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $200.00",
      "Descuento:               -$40.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $160.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $160.00",
      "Pago con:                $160.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "     RECOMPENSAS REVERTIDAS     ",
      "Canjes revertidos:             1",
      "Puntos devueltos:            +40",
      "--------------------------------",
      "Canje revertido #1",
      "DESCUENTO 20%",
      "Tipo: DESCUENTO EN PRODUCTO",
      "Desc. revertido:         +$40.00",
      "Producto: CROQUETAS",
      "Cantidad:                     x1",
      "Puntos devueltos:            +40",
      "Motivo reversa:",
      "Reverso por cancelación",
      "--------------------------------",
      "    *** VENTA CANCELADA ***     ",
      "Fecha cancelación: 16/9/2026",
      "Hora cancelación : 07:45 a.m.",
      "Motivo:",
      "Cliente canceló",
      "Método reembolso: TRANSFERENCIA",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("9. devoluciones parciales con ítems", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA009",
        created_at: "2026-09-16T09:00:00.000Z",
        subtotal: 300,
        tax: 48,
        total: 348,
        amount_received: 348,
        change_amount: 0,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 348 }],
        status: "completed",
        total_returned: 87,
        net_total: 261,
        points_returned: 10,
        customer_name: "María López",
        customer_phone: "998 555 0101",
        points_earned: 20,
        customer_points_balance: 150,
        returns: [
          {
            created_at: "2026-09-16T13:00:00.000Z",
            refund_method: "Efectivo",
            total_refund: 87,
            return_reason: "Producto dañado",
            points_returned: 10,
            items: [{ quantity: 1, description: "Snack", total_price: 87 }],
          },
        ],
      },
      items: [{ quantity: 2, description: "Croquetas", unit_price: 150, original_unit_price: 150, final_unit_price: 150, line_total: 300 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 04:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA009",
      "Cliente: MARÍA LÓPEZ",
      "Tel. cliente: 998 555 0101",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "2    CROQUETAS            300.00",
      "     P.U. $150.00",
      "",
      "--------------------------------",
      "Artículos: 2",
      "Subtotal:                $300.00",
      "IVA 16%:                  $48.00",
      "TOTAL:                   $348.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $348.00",
      "Pago con:                $348.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "       PUNTOS DEL CLIENTE       ",
      "Puntos ganados:              +20",
      "Puntos devolución:           -10",
      "Puntos netos:                +10",
      "Saldo puntos:            150 pts",
      "--------------------------------",
      " *** DEVOLUCIONES PARCIALES *** ",
      "Devuelto acum.:           $87.00",
      "Neto actual:             $261.00",
      "Puntos devolución:           -10",
      "--------------------------------",
      "Devolución #1",
      "Fecha: 16/9/2026",
      "Hora : 08:00 a.m.",
      "Método: EFECTIVO",
      "Monto devuelto:           $87.00",
      "Puntos desc.:                -10",
      "Motivo:",
      "Producto dañado",
      "--------------------------------",
      "Cant Devuelto            Importe",
      "--------------------------------",
      "1    SNACK                 87.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("10. ítem kit con componentes", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA010",
        created_at: "2026-09-16T14:00:00.000Z",
        subtotal: 220,
        tax: 0,
        total: 220,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 220 }],
        status: "completed",
      },
      items: [
        { quantity: 1, description: "Kit Baño Completo", unit_price: 220, line_total: 220, is_kit: true, components: [{ name: "Shampoo", quantity: 1 }, { name: "Cepillo", quantity: 2 }] },
      ],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 09:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA010",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    KIT BAÑO COMPLETO    220.00",
      "     (KIT)                      ",
      "     P.U. $220.00",
      "     - SHAMPOO X1               ",
      "     - CEPILLO X2               ",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $220.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $220.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $220.00",
      "Pago con:                $220.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("11. reimpresión (isReprint con reprintedAt fijo)", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA011",
        created_at: "2026-09-16T08:00:00.000Z",
        subtotal: 50,
        tax: 8,
        total: 58,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 58 }],
        status: "completed",
        notes: "",
      },
      items: [{ quantity: 1, description: "Galletas", unit_price: 58, original_unit_price: 58, final_unit_price: 58, line_total: 58 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
      isReprint: true,
      reprintedAt: "2026-09-16T18:00:00.000Z",
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 03:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA011",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    GALLETAS              58.00",
      "     P.U. $58.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                 $50.00",
      "IVA 16%:                   $8.00",
      "TOTAL:                    $58.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                 $58.00",
      "Pago con:                 $58.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "    *** COPIA DE TICKET ***     ",
      "Reimpreso: 16/9/2026 01:00 p.m.",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("12. descripción y dirección largas (wrapping)", () => {
    const input = {
      branch: {
        name: "Sucursal Plaza Las Américas Boulevard Kukulcán",
        phone: "998 222 4455",
        address: "Avenida Costera de las Américas No. 55, Manzana 12, Lote 3, 77500",
        city: "Cancún",
        state: "QUINTANA ROO",
      },
      sale: {
        folio: "VENTA012",
        created_at: "2026-09-16T15:30:00.000Z",
        subtotal: 500,
        tax: 0,
        total: 500,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 500 }],
        status: "completed",
      },
      items: [{ quantity: 1, description: "Alimento balanceado para cachorros raza pequena con alto contenido proteico", unit_price: 500, original_unit_price: 500, final_unit_price: 500, line_total: 500 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "SUCURSAL PLAZA LAS AMÉRICAS BOULEVARD KUKULCÁN",
      "AVENIDA COSTERA DE LAS AMÉRICAS ",
      "       NO. 55 MZ 12 LT 3        ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 222 4455        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 10:30 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA012",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    ALIMENTO             500.00",
      "     BALANCEADO PARA            ",
      "     CACHORROS RAZA             ",
      "     PEQUENA CON ALTO           ",
      "     CONTENIDO                  ",
      "     PROTEICO                   ",
      "     P.U. $500.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $500.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $500.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $500.00",
      "Pago con:                $500.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });

  it("13. notas y footer", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA013",
        created_at: "2026-09-16T16:00:00.000Z",
        subtotal: 120,
        tax: 0,
        total: 120,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 120 }],
        status: "completed",
        notes: "Servicio a domicilio. Entregar en la puerta principal.",
      },
      items: [{ quantity: 1, description: "Pecera", unit_price: 120, original_unit_price: 120, final_unit_price: 120, line_total: 120 }],
      cashierName: "LAURA GARCIA",
      footer: { line1: "Visítanos en línea", line2: "", phone: "998 999 8877", returnPolicy: "Devoluciones solo con ticket" },
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 11:00 a.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA013",
      "Cliente: PÚBLICO EN GENERAL",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    PECERA               120.00",
      "     P.U. $120.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $120.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $120.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $120.00",
      "Pago con:                $120.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "Notas:",
      "Servicio a domicilio. Entregar",
      "en la puerta principal.",
      "--------------------------------",
      "Visítanos en línea",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 999 8877",
      "",
      "Devoluciones solo con ticket",
      "================================",
    ].join("\n"));
  });

  it("14. cliente con puntos (ganados/devueltos/canjeados/saldo)", () => {
    const input = {
      branch: BASE_BRANCH,
      sale: {
        folio: "VENTA014",
        created_at: "2026-09-16T17:30:00.000Z",
        subtotal: 100,
        tax: 0,
        total: 100,
        payment_method: "EFECTIVO",
        payments: [{ payment_method_name: "Efectivo", amount: 100 }],
        status: "completed",
        customer_name: "Juan Pérez",
        customer_phone: "998 000 1122",
        points_earned: 15,
        customer_points_balance: 320,
      },
      items: [{ quantity: 1, description: "Shampoo", unit_price: 100, original_unit_price: 100, final_unit_price: 100, line_total: 100 }],
      cashierName: "LAURA GARCIA",
      footer: BASE_FOOTER,
    };

    expect(buildTicketText(input)).toBe([
      "================================",
      "            CROKETS             ",
      "        SUCURSAL CENTRO         ",
      "       AV. XUCHIL 5 SM 34       ",
      "     CANCÚN, QROO CP 77500      ",
      "       Tel. 998 111 2233        ",
      "================================",
      "Fecha: 16/9/2026",
      "Hora : 12:30 p.m.",
      "Cajero: LAURA GARCIA",
      "Folio : VENTA014",
      "Cliente: JUAN PÉREZ",
      "Tel. cliente: 998 000 1122",
      "--------------------------------",
      "Cant Descripción         Importe",
      "--------------------------------",
      "1    SHAMPOO              100.00",
      "     P.U. $100.00",
      "",
      "--------------------------------",
      "Artículos: 1",
      "Subtotal:                $100.00",
      "IVA 16%:                   $0.00",
      "TOTAL:                   $100.00",
      "--------------------------------",
      "Método de pago: EFECTIVO",
      "EFECTIVO:                $100.00",
      "Pago con:                $100.00",
      "Cambio:                    $0.00",
      "--------------------------------",
      "       PUNTOS DEL CLIENTE       ",
      "Puntos ganados:              +15",
      "Saldo puntos:            320 pts",
      "--------------------------------",
      "Gracias por su compra",
      "",
      "Agenda tu cita de baño",
      "Tel. 998 117 5387",
      "",
      "Para cambios o devoluciones",
      "presentar ticket de compra",
      "================================",
    ].join("\n"));
  });
});
